CREATE TABLE IF NOT EXISTS tags_task (
  tag_id VARCHAR(36) NOT NULL,
  task_id VARCHAR(36) NOT NULL,
  PRIMARY KEY (tag_id, task_id),
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE,
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);